// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBreachEvent struct {
	_         structs.HostLayout
	NsKey     uint64
	Cgid      uint64
	Pid       uint32
	Reason    uint32
	Timestamp uint64
	TopCgid   uint64
}

type bpfCpuLease struct {
	_           structs.HostLayout
	Count       uint64
	LeaseBudget uint64
	LastUsedNs  uint64
	TopCgid     uint64
	TopCount    uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents            = "events"
	bpfMapFdCgroup          = "fd_cgroup"
	bpfMapFdCgroupCounter   = "fd_cgroup_counter"
	bpfMapFdNsCounter       = "fd_ns_counter"
	bpfMapFdNsLimit         = "fd_ns_limit"
	bpfMapProcCgroup        = "proc_cgroup"
	bpfMapProcCgroupCounter = "proc_cgroup_counter"
	bpfMapProcNsCounter     = "proc_ns_counter"
	bpfMapProcNsLimit       = "proc_ns_limit"
	bpfProgTrackClone       = "track_clone"
	bpfProgTrackCloseFd     = "track_close_fd"
	bpfProgTrackExit        = "track_exit"
	bpfProgTrackInstallFd   = "track_install_fd"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TrackClone     *ebpf.ProgramSpec `ebpf:"track_clone"`
	TrackCloseFd   *ebpf.ProgramSpec `ebpf:"track_close_fd"`
	TrackExit      *ebpf.ProgramSpec `ebpf:"track_exit"`
	TrackInstallFd *ebpf.ProgramSpec `ebpf:"track_install_fd"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events            *ebpf.MapSpec `ebpf:"events"`
	FdCgroup          *ebpf.MapSpec `ebpf:"fd_cgroup"`
	FdCgroupCounter   *ebpf.MapSpec `ebpf:"fd_cgroup_counter"`
	FdNsCounter       *ebpf.MapSpec `ebpf:"fd_ns_counter"`
	FdNsLimit         *ebpf.MapSpec `ebpf:"fd_ns_limit"`
	ProcCgroup        *ebpf.MapSpec `ebpf:"proc_cgroup"`
	ProcCgroupCounter *ebpf.MapSpec `ebpf:"proc_cgroup_counter"`
	ProcNsCounter     *ebpf.MapSpec `ebpf:"proc_ns_counter"`
	ProcNsLimit       *ebpf.MapSpec `ebpf:"proc_ns_limit"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events            *ebpf.Map `ebpf:"events"`
	FdCgroup          *ebpf.Map `ebpf:"fd_cgroup"`
	FdCgroupCounter   *ebpf.Map `ebpf:"fd_cgroup_counter"`
	FdNsCounter       *ebpf.Map `ebpf:"fd_ns_counter"`
	FdNsLimit         *ebpf.Map `ebpf:"fd_ns_limit"`
	ProcCgroup        *ebpf.Map `ebpf:"proc_cgroup"`
	ProcCgroupCounter *ebpf.Map `ebpf:"proc_cgroup_counter"`
	ProcNsCounter     *ebpf.Map `ebpf:"proc_ns_counter"`
	ProcNsLimit       *ebpf.Map `ebpf:"proc_ns_limit"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.FdCgroup,
		m.FdCgroupCounter,
		m.FdNsCounter,
		m.FdNsLimit,
		m.ProcCgroup,
		m.ProcCgroupCounter,
		m.ProcNsCounter,
		m.ProcNsLimit,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TrackClone     *ebpf.Program `ebpf:"track_clone"`
	TrackCloseFd   *ebpf.Program `ebpf:"track_close_fd"`
	TrackExit      *ebpf.Program `ebpf:"track_exit"`
	TrackInstallFd *ebpf.Program `ebpf:"track_install_fd"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TrackClone,
		p.TrackCloseFd,
		p.TrackExit,
		p.TrackInstallFd,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
